version: '3.8'

services:
  audio_frontend:
    image: ghcr.io/ghost-love-you/audio_frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - audio-files:/app/audio_files
    restart: always

  audio_backend:
    image: ghcr.io/ghost-love-you/audio_backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - audio-files:/app/audio_files
    restart: always

volumes:
  audio-files:
